const { Question } = require("../models");

const questiondata = [
  {
    quiz_id: 1,
    question: "What is the name of the corporate supermarket in Stardew Valley",
    answer1: "Walmart",
    answer2: "JojaMart",
    answer3: "MegaMart",
    answer4: "Frank",
    correct: "JojaMart",
  },
  {
    quiz_id: 1,
    question: "What is the name of the town in Stardew Valley",
    answer1: "Pelican Town",
    answer2: "Ginger Town",
    answer3: "Stardew Valley",
    answer4: "Frank",
    correct: "Pelican Town",
    img_url: "https://stardewvalleywiki.com/mediawiki/images/4/43/Map.png",
  },
  {
    quiz_id: 1,
    question: "What are the creatures found in the community center called?",
    answer1: "Sprites",
    answer2: "Junimos",
    answer3: "Apples",
    answer4: "Frank",
    correct: "Junimos",
    img_url:
      "https://i.etsystatic.com/9694683/r/il/dc5ea9/1594443656/il_570xN.1594443656_nvma.jpg",
  },
  {
    quiz_id: 1,
    question: "How do you get your farm?",
    answer1: "You buy it",
    answer2: "You inherit it",
    answer3: "You steal it",
    answer4: "You find it",
    correct: " You inherit it",
  },
  {
    quiz_id: 2,
    question: "What is the difference between a While and Do While loop?",
    answer1: "About 3 characters",
    answer2: "a do while will always run once",
    answer3: "a while loop checks at the end of the loop",
    answer4: "they are the same",
    correct: "a do while will always run once",
  },
  {
    quiz_id: 2,
    question: "How do you define a function in JavaScript?",
    answer1: "def myFunc()",
    answer2: "new myFunc()",
    answer3: "function myFunc()",
    answer4: "create myFunc()",
    correct: "function myFunc()",
  },
  {
    quiz_id: 2,
    question: "Where should you put the JavaScript tag?",
    answer1: "In the body",
    answer2: "In the header",
    answer3: "In the footer",
    answer4: "In the HTML tag",
    correct: "In the body",
  },
  {
    quiz_id: 2,
    question: "How do you write Hello Word in an alert box?",
    answer1: "alert(Hello World);",
    answer2: "msg(Hello World);",
    answer3: "alertBox(Hello World);",
    answer4: "msgBox(Hello World);",
    correct: "alert(Hello World);"
  },
  {
    quiz_id: 3,
    question: "How much damage does a maxed-out MK-7 assault rifle do?",
    answer1: "50",
    answer2: "22",
    answer3: "31",
    answer4: "90",
    correct: "22",
  },
  {
    quiz_id: 3,
    question: "What is the main currency called?",
    answer1: "V-bucks",
    answer2: "Fortnite Gold",
    answer3: "Platinum Coins",
    answer4: "Bazuka Bucks",
    correct: "V-bucks"
  },
  {
    quiz_id: 3,
    question: "What is the rarest skin in Fortnite?",
    answer1: "Vageta Skin",
    answer2: "Ariana Grande Skin",
    answer3: "Aerial Assault Trooper Skin",
    answer4: "Rick Sanchez Skin",
    correct: "Aerial Assault Trooper Skin"
  },
  {
    quiz_id: 3,
    question: "How many players can win a Battle Royale?",
    answer1: "5",
    answer2: "15",
    answer3: "2",
    answer4: "1",
    correct: "1"
  },
  {
    quiz_id: 4,
    question: "What is the first slime you meet?",
    answer1: "Pink slime",
    answer2: "Rock slime",
    answer3: "Mosaic slime",
    answer4: "The tarr",
    correct: "Pink slime",
  },
  {
    quiz_id: 4,
    question: "What is the cat slime called?",
    answer1: "The tarr",
    answer2: "Cotton slime",
    answer3: "Hunter slime",
    answer4: "The tabby",
    correct: "The tabby",
    img_url: "https://static.wikia.nocookie.net/slimerancher/images/9/94/Tabby_Slime_SP.png/revision/latest/scale-to-width-down/350?cb=20170401125706",
  },
  {
    quiz_id: 4,
    question: "What is the rarest slime in the game",
    answer1: "Lucky slime",
    answer2: "Twinkle slime",
    answer3: "Quantum slime",
    answer4: "Gold slime",
    correct: "Gold slime",
  },
  {
    quiz_id: 4,
    question: "What year was slime rancher released?",
    answer1: "2020",
    answer2: "2015",
    answer3: "2016",
    answer4: "2017",
    correct: "2016"
  },
  {
    quiz_id: 5,
    question: "Who is this character?",
    answer1: "Minecraft Steve",
    answer2: "Minecraft Joe",
    answer3: "Minecraft Tim",
    answer4: "Minecraft John",
    correct: "Minecraft Steve",
    img_url: "https://www.smashbros.com/assets_v2/img/fighter/steve/main.png"
  },
  {
    quiz_id: 5, 
    question: "What must you use to mine ores and stones?",
    answer1: "Shovel",
    answer2: "Gun",
    answer3: "Pickaxe",
    answer4: "TNT",
    correct: "Pickaxe"
  },
  {
    quiz_id: 5,
    question: "What problem does a tonic cure?",
    answer1: "Nausea",
    answer2: "Vampirism",
    answer3: "Hunger",
    answer4: "Zombification",
    correct: "Nausea"
  },
  {
    quiz_id: 5,
    question: "What happens when you swim near a dolphin?",
    answer1: "It attacks you",
    answer2: "You can befriend it",
    answer3: "You swim faster",
    answer4: "You can ride it",
    correct: "You swim faster"
  },
  {
    quiz_id: 6,
    question: "Who is this champion?",
    answer1: "Jim",
    answer2: "Fluffy",
    answer3: "Teemo",
    answer4: "Hammy",
    correct: "Teemo",
    img_url: "https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Teemo_0.jpg"
  },
  {
    quiz_id: 6,
    question: "Who is this champion?",
    answer1: "Kayle",
    answer2: "Morgana",
    answer3: "Claire",
    answer4: "Syndra",
    correct: "Morgana",
    img_url: "https://cdn1.dotesports.com/wp-content/uploads/2022/05/11084717/maxresdefault-9.jpg",
  },
  {
    quiz_id: 6,
    question: "Who is this champion?",
    answer1: "Master Yi",
    answer2: "Cool Guy Steve",
    answer3: "Yasuo",
    answer4: "Nerf Him Pls",
    correct: "Master Yi",
    img_url: "https://cdn1.dotesports.com/wp-content/uploads/2022/05/11084717/maxresdefault-9.jpg",
  },
  {
    quiz_id: 6,
    question: "Who is this champion?",
    answer1: "Kai'sa",
    answer2: "Lulu",
    answer3: "Irelia",
    answer4: "Akali",
    correct: "Akali",
    img_url: "https://cdn1.dotesports.com/wp-content/uploads/2022/05/11084717/maxresdefault-9.jpg",
  },
  {
    quiz_id: 7,
    question: "What is this food?",
    answer1: "A burger",
    answer2: "A pizza",
    answer3: "Bacon",
    answer4: "A Cookie",
    correct: "A burger",
    img_url: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8YnVyZ2VyfGVufDB8fDB8fA%3D%3D&w=1000&q=80"
  },
  {
    quiz_id: 7,
    question: "What is this food?",
    answer1: "A cookie",
    answer2: "Ice cream",
    answer3: "Macron",
    answer4: "Brownie",
    correct: "A cookie",
    img_url: "https://www.cookingclassy.com/wp-content/uploads/2014/06/chocolate-chip-cookie-16.jpg"
  },
  {
    quiz_id: 7,
    question: "What is this food?",
    answer1: "A salad",
    answer2: "An onion",
    answer3: "French Fries",
    answer4: "Freedom Fries",
    correct: "French Fries",
    img_url: "https://media.istockphoto.com/photos/potatoes-fries-in-a-red-carton-box-isolated-fast-food-picture-id496094410?k=20&m=496094410&s=612x612&w=0&h=BH41-IaJ-pnGS2BsKRSBL1DtoD-lpc_xtnJQz2jEkOY="
  },
  {
    quiz_id: 7,
    question: "What is this food?",
    answer1: "Nachos",
    answer2: "Bread",
    answer3: "Pizza",
    answer4: "Cinnamon Roll",
    correct: "Pizza",
    img_url: "https://www.budgetbytes.com/wp-content/uploads/2010/07/Classic-Homemade-Pizza-Dough-close.jpg",
  },
  {
    quiz_id: 8,
    question: "What is the name of the villain in Hercules?",
    answer1: "Hades",
    answer2: "Ares",
    answer3: "Phil",
    answer4: "Zeus",
    correct: "Hades"
  },
  {
    quiz_id: 8,
    question: "What did Cinderella leave behind at the ball?",
    answer1: "Her headband",
    answer2: "Her ring",
    answer3: "Her slipper",
    answer4: "Her necklace",
    correct: "Her slipper",
  },
  {
    quiz_id: 8,
    question: "What is the name of Andy's neighbor in Toy Story?",
    answer1: "Johnathon",
    answer2: "Brad",
    answer3: "James",
    answer4: "Sid",
    correct: "Sid"
  },
  {
    quiz_id: 8,
    question: "What does Hakuna Matata mean?",
    answer1: "See you later!",
    answer2: "No Worries",
    answer3: "I love you!",
    answer4: "Family",
    correct: "No Worries"
  },
  {
    quiz_id: 9,
    question: "What is the name of this app?",
    answer1: "Twitter",
    answer2: "Facebook",
    answer3: "Instagram",
    answer4: "Snapchat",
    correct: "Twitter",
    img_url: "https://www.iconpacks.net/icons/2/free-twitter-logo-icon-2429-thumb.png",
  },
  {
    quiz_id: 9,
    question: "What is the name of this app?",
    answer1: "Twitch",
    answer2: "Twitter",
    answer3: "Snapchat",
    answer4: "Pintrest",
    correct: "Pintrest",
    img_url: "https://cdn-icons-png.flaticon.com/512/174/174863.png"
  },
  {
    quiz_id: 9,
    question: "What is the name of this app?",
    answer1: "Pintrest",
    answer2: "Instagram",
    answer3: "Facebook",
    answer4: "Zoom",
    correct: "Zoom",
    img_url: "https://cdn.icon-icons.com/icons2/2428/PNG/512/zoom_black_logo_icon_147040.png",
  },
  {
    quiz_id: 9,
    question: "What is the name of this app?",
    answer1: "Zoom",
    answer2: "Facebook",
    answer3: "Snapchat",
    answer4: "Instagram",
    correct: "Snapchat",
    img_url: "https://1000logos.net/wp-content/uploads/2017/08/Snapchat-logo.png"
  },
  {
    quiz_id: 10,
    question: "How long is an Olympic swimming pool(in meters)?",
    answer1: "40 meters",
    answer2: "45 meteres",
    answer3: "50 meters",
    answer4: "55 meters",
    correct: "50 meters"
  },
  {
    quiz_id: 10,
    question: "What is cynophobia?",
    answer1: "Fear of dogs",
    answer2: "Fear of psychos",
    answer3: "Fear of potatoes",
    answer4: "Fear of cyndaquil",
    correct: "Fear of dogs"
  },
  {
    quiz_id: 10,
    question: "Who was the first dictionary written by?",
    answer1: "John Webster",
    answer2: "Sebation Miriam",
    answer3: "Robert Cawdrey",
    answer4: "John Cawdrey",
    correct: "Robert Cawdrey"
  },
  {
    quiz_id: 10,
    question: "What was the first soft drink in space?",
    answer1: "Sprite",
    answer2: "Bud Weiser Beer",
    answer3: "Pepsi",
    answer4: "Coca Cola",
    correct: "Coca Cola"
  },
];

const seedQuestion = () => Question.bulkCreate(questiondata);

module.exports = seedQuestion;